# Generated by Django 5.1.2 on 2024-11-09 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryform',
            name='task_category',
        ),
    ]
