# Generated by Django 5.1.2 on 2024-11-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0002_remove_categoryform_task_category'),
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='task_category',
            field=models.ManyToManyField(to='task_category.categoryform'),
        ),
    ]
